{
 "title": "docker logs my",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Celery",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"celery\"} |= ``"
    }
   ]
  },
  {
   "title": "Cron",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"natures-cart_cron_1\"} |= ``"
    }
   ]
  },
  {
   "title": "Web",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"natures-cart_web_1\"} |= ``"
    }
   ]
  }
 ]
}