server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag
  - timestamp:
      format: RFC3339Nano
      source: time
  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
  - output:
      source: output



# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0

# positions:
#   filename: /tmp/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: flog_scrape
#     docker_sd_configs:
#       - host: unix:///var/run/docker.sock
#         refresh_interval: 5s
#         # filters:
#         #   - name: label
#         #     values: ["logging=promtail"]
#     relabel_configs:
#       - source_labels: ['__meta_docker_container_name']
#         regex: '/(.*)'
#         target_label: 'container'
#       - source_labels: ['__meta_docker_container_log_stream']
#         target_label: 'logstream'
#       - source_labels: ['__meta_docker_container_label_logging_jobname']
#         target_label: 'job'



# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0

# positions:
#   filename: /tmp/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: docker_scrape
#     docker_sd_configs:
#       - host: unix:///var/run/docker.sock
#         refresh_interval: 5s
#     relabel_configs:
#       # Filter by service name (container name) for web and celery
#       - source_labels: ['__meta_docker_container_name']
#         regex: '(web|celery)'   # This will only match containers named 'web' and 'celery'
#         action: keep
#       - source_labels: ['__meta_docker_container_name']
#         target_label: 'container'
#       - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
#         target_label: 'service'
#       - source_labels: ['__meta_docker_container_log_stream']
#         target_label: 'logstream'
#       - source_labels: ['__meta_docker_container_label_logging_jobname']
#         target_label: 'job'

