global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']


alerting:
  alertmanagers:
    - static_configs:
        - targets: ['prometheus-msteams:2000']


rule_files:
  - "alert_rules.yml"

