# alertmanager.yml

global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'prometheus-msteams'

receivers:
  - name: 'prometheus-msteams'
    webhook_configs:
      - send_resolved: true
        url: 'http://prometheus-msteams:2000/alertmanager'